### ISSUE TITLE
No work for "github.com/json-iterator/go"

### ISSUE THREAD

**Issue by shumkovdenis** [tmzane/musttag#51]
Linter does not work for github.com/json-iterator/go . Below is an example of the code and settings

```go
package main

import (
	jsoniter "github.com/json-iterator/go"
)

type Foo struct {
	Bar string
}

func main() {
	foo := &Foo{Bar: "bar"}
	jsoniter.Marshal(foo)
}
```

.golangci.yml

```yml
linters-settings:
  musttag:
    functions:
        # The full name of the function, including the package.
      - name: github.com/json-iterator/go/Marshal
        # The struct tag whose presence should be ensured.
        tag: json
        # The position of the argument to check.
        arg-pos: 1
```
OR
```yml
linters-settings:
  musttag:
    functions:
        # The full name of the function, including the package.
      - name: github.com/json-iterator/go/jsoniter .Marshal
        # The struct tag whose presence should be ensured.
        tag: json
        # The position of the argument to check.
        arg-pos: 1
```

**Comment by tmzane** [comment]
Hi, I believe it should be

```yaml
linters-settings:
  musttag:
    functions:
      - name: github.com/json-iterator/go.Marshal
        tag: json
        arg-pos: 0
```

Note that `arg-pos` is 0 not 1, since the count starts from 0. Let me know if it works for you!
